INSERT INTO "teams" ("id", "name", "image", "created_at", "updated_at") 
VALUES
(1, 'Qatar', 'qatar.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Ecuador', 'ecuador.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Senegal', 'senegal.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Netherlands', 'netherlands.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'England', 'england.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'IR Iran', 'ir-iran.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'USA', 'usa.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Wales', 'wales.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'Argentina', 'argentina.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'Saudi Arabia', 'saudi-arabia.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'Mexico', 'mexico.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'Poland', 'poland.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'France', 'france.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'Denmark', 'denmark.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'Tunisia', 'tunisia.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'Australia', 'australia.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'Spain', 'spain.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'Germany', 'germany.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'Japan', 'japan.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'Costa Rica', 'costa-rica.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'Belgium', 'belgium.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Canada', 'canada.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 'Morocco', 'morocco.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 'Croatia', 'croatia.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 'Brazil', 'brazil.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'Serbia', 'serbia.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 'Switzerland', 'switzerland.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 'Cameroon', 'cameroon.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 'Portugal', 'portugal.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 'Ghana', 'ghana.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 'Uruguay', 'uruguay.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 'Korea Republic', 'korea-republic.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);